//====================================================================================================================================================
// Copyright 2025 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.25.00.05
// Generated on Sunday, February 16, 2025 5:48:03 PM

// C++ Includes
#include <string>

// FRC includes

// Team 302 includes
#include "mechanisms/ClimberManager/ClimbState.h"
#include "teleopcontrol/TeleopControl.h"
#include "teleopcontrol/TeleopControlFunctions.h"
#include "utils/logging/debug/Logger.h"

// Third Party Includes

using namespace std;
using namespace ClimberManagerStates;

/// @class ExampleForwardState
/// @brief information about the control (open loop, closed loop position, closed loop velocity, etc.) for a mechanism state
ClimbState::ClimbState(std::string stateName,
					   int stateId,
					   ClimberManager *mech,
					   RobotIdentifier activeRobotId) : State(stateName, stateId), m_mechanism(mech), m_RobotId(activeRobotId)
{
}

void ClimbState::Init()
{
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("ClimbState"), string("Init"));
}

void ClimbState::InitPRACTICE_BOT9999()
{
}

void ClimbState::InitCOMP_BOT302()
{
}

void ClimbState::Run()
{

	double manualClimberPercent = TeleopControl::GetInstance()->GetAxisValue(TeleopControlFunctions::MANUAL_CLIMB_UP) - TeleopControl::GetInstance()->GetAxisValue(TeleopControlFunctions::MANUAL_CLIMB_DOWN);
	auto climberPosition = m_mechanism->GetClimber()->GetPosition().GetValue();

	// if (TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::AUTO_ALIGN_BARGE)) // Auto Climb button is Y (Mapped to Drive To Barge)
	// {
	// 	m_mechanism->UpdateTargetClimberPositionDegree(m_ClimberTarget);
	// }
	// else
	// {

	if (climberPosition < m_ClimberTarget)
		m_mechanism->UpdateTargetClimberPercentOut(m_holdPercentOut);

	if (climberPosition > m_minClimbPosition)
	{
		if ((abs(manualClimberPercent) > 0.075))
		{
			// double climberPercentOutTarget = m_mechanism->GetClimber()->GetPosition().GetValue() > 90.0_tr ? std::clamp(manualClimberPercent * m_percentOutScale, -0.35, 0.35) : manualClimberPercent * m_percentOutScale;
			double climberPercentOutTarget = manualClimberPercent * m_percentOutScale;
			m_mechanism->UpdateTargetClimberPercentOut(climberPercentOutTarget);
		}
		else
			// m_mechanism->UpdateTargetClimberPositionDegree(m_mechanism->GetClimber()->GetPosition().GetValue());
			m_mechanism->UpdateTargetClimberPercentOut(0.0);
	}
	else
	{
		m_mechanism->UpdateTargetClimberPercentOut(0.0);
	}
}

void ClimbState::Exit()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("ClimbState"), string("Exit"));
}

bool ClimbState::AtTarget()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("ClimbState"), string("AtTarget"));

	bool atTarget = false;
	return atTarget;
}

bool ClimbState::IsTransitionCondition(bool considerGamepadTransitions)
{
	// To get the current state use m_mechanism->GetCurrentState()

	return ((m_mechanism->GetCurrentState() == ClimberManager::STATE_DELIVER_CLIMBER) && m_mechanism->AtTarget());

	// return (considerGamepadTransitions && TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::EXAMPLE_MECH_FORWARD));
}
