//====================================================================================================================================================
// Copyright 2025 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.25.00.05
// Generated on Sunday, February 16, 2025 8:51:02 PM

// C++ Includes
#include <string>

// FRC includes

// Team 302 includes
#include "mechanisms/DragonTale/GrabAlgaeFloorState.h"
#include "teleopcontrol/TeleopControl.h"
#include "teleopcontrol/TeleopControlFunctions.h"
#include "utils/logging/debug/Logger.h"

// Third Party Includes

using namespace std;
using namespace DragonTaleStates;

/// @class ExampleForwardState
/// @brief information about the control (open loop, closed loop position, closed loop velocity, etc.) for a mechanism state
GrabAlgaeFloorState::GrabAlgaeFloorState(std::string stateName,
										 int stateId,
										 DragonTale *mech,
										 RobotIdentifier activeRobotId) : State(stateName, stateId), m_mechanism(mech), m_RobotId(activeRobotId)
{
}

void GrabAlgaeFloorState::Init()
{
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("GrabAlgaeFloorState"), string("Init"));

	if (m_RobotId == RobotIdentifier::PRACTICE_BOT_9999)
		InitPRACTICE_BOT9999();
	else if (m_RobotId == RobotIdentifier::COMP_BOT_302)
		InitCOMP_BOT302();

	m_mechanism->UpdateTargetCoralPercentOutput(m_CoralTarget);
	m_mechanism->SetArmTarget(m_ArmTarget);
	m_mechanism->SetElevatorTarget(m_ElevatorLeaderTarget);
}

void GrabAlgaeFloorState::InitPRACTICE_BOT9999()
{
	m_mechanism->UpdateTargetAlgaeTalonFXPercentOutput(m_AlgaeTarget);
}

void GrabAlgaeFloorState::InitCOMP_BOT302()
{
	m_mechanism->UpdateTargetAlgaeTalonFXSPercentOutput(m_AlgaeTarget);
}

void GrabAlgaeFloorState::Run()
{
	if (TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::ALGAE_HIGH))
	{
		m_mechanism->SetArmTarget(m_ArmTargetLollipop);
		m_mechanism->SetElevatorTarget(m_ElevatorLeaderTargetLollipop);
	}
	else if (TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::ALGAE_LOW))
	{
		m_mechanism->SetArmTarget(m_ArmTarget);
		m_mechanism->SetElevatorTarget(m_ElevatorLeaderTarget);
	}

	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("GrabAlgaeFloorState"), string("Run"));
}

void GrabAlgaeFloorState::Exit()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("GrabAlgaeFloorState"), string("Exit"));
}

bool GrabAlgaeFloorState::AtTarget()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("GrabAlgaeFloorState"), string("AtTarget"));

	bool atTarget = false;
	return atTarget;
}

bool GrabAlgaeFloorState::IsTransitionCondition(bool considerGamepadTransitions)
{
	// To get the current state use m_mechanism->GetCurrentState()

	return (considerGamepadTransitions && (TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::ALGAE_INTAKE)));
}
